label encoding

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
#create a df
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [5]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [6]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [9]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\asus\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [10]:
lbl_encoder.transform([['red']])

c:\Users\asus\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

ordinal encoding

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [13]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [14]:
#create an instance of ordinal encoder then fit transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [15]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [16]:
encoder.transform([['small']])

c:\Users\asus\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])